apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: mini-commerce
    labels:
        app.kubernetes.io/part-of: mini-commerce
type: Opaque
stringData:
    DATABASE_USERNAME: ENC[AES256_GCM,data:1y/JboT4y7wWLMbQ,iv:FsCQxqdR+3nXcjbcPn8xwX0+/4b/Ce229V0+dzJr4aY=,tag:ESi0lST0lFDaN4Ht2zn+Pg==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:1BOU//pfJiZJN2g/,iv:NEPrQKanIn2iREUy+v/B3h2mPR28zc9SiknikslkoSo=,tag:iBZATx+8kGAiFuNBWJTNMg==,type:str]
    REDIS_PASSWORD: ""
    BFF_SECRET_KEY: ENC[AES256_GCM,data:So+drGorQStstmyGhMTgcqSbA/9Y2A==,iv:LsEbqI/+AKIlgR4t7QlLRIEUnMsszDYT7BCp5RlZUhY=,tag:TrFm/vYRW1bW2Ka7DqkJ5g==,type:str]
    SUPABASE_SERVICE_ROLE_KEY: ENC[AES256_GCM,data:RLjhsHd+siod2IO4cgBH7DuKvApt4Icq2Az/86+5X0y2psd38A6tMP8h9f160CikEg6nnwGf2X5RYCQWjkwazovNE0fasjHeBCOOk2UoGhw/Nm5HMR8qaLcmk8/nIXSrHH2m5L81O7IiiYNJp9jNVvaRELALYTU31wU9GhZWvZQDHB0YZC8MxTPCKSckgDx77Q57TcufkMlLIlNSXm6agzL5qbq3l3MNbGKD62gO2myHaeUIdJm96ab+hkjJ43jsjDFJ7RiVyozXEqlWMxFFjHfByVV1/bhTNdJx,iv:wMYH+4rZO7hHScxqNgvt6v8j+OS+A+zldVYegCLzHzI=,tag:aUHeS0qyZoZx/B+EiEY6jA==,type:str]
    TOSS_SECRET_KEY: ENC[AES256_GCM,data:lFaUM7QWC+tB8gSSFtAKVf5fv/qVyp83T2QChwwQvsS9mJ6WPKU=,iv:0AnZ58/J74y+I58GXUFNdkBJy5RTwGH+yN6X0nE5wnM=,tag:HAbK3qG6cAvx82elCEpshg==,type:str]
    #ENC[AES256_GCM,data:MGHFunyeKWxAlH8tcUTn/fnJqZNMaZp9qG2818SRO1LO96k68JZR9ei8nqLoINf5Czl71uNBjiQj2skfBh7TuNbZZ5LfJZ+flf8OGy4vDSLRLD2QSBQgTwAr2r+nIy4EQv4bH0ovRwS56ynJJw==,iv:2iVGdtMKo5i268MzTYs8ItbOH7Rk24NX93icHX8tzKQ=,tag:90BTMS6qGHiLaKOaRLZ5Bg==,type:comment]
    #ENC[AES256_GCM,data:eSDOQs3uscdDD9Dt5eSlwOJ5x7Rg/1+JcOo3F02pug43dT6wQ+WTSxxpbcKg9waBZzh+Z/GXszCj6kpbnZGLe2qe2Qpl862VGMLLuVSOLbgfWmM4ozJxOiL0jBE9qmkz8DkIuNN9ERVFjJiVfx46l2GxUv+ulFbAI8cHcz7AMXjccmU=,iv:duhRrkvQVQtoEcEPYL+3xiYaXfV8vbiCBZDdyzLIGqs=,tag:jYEJaxQ5ciqzYfxacfpA/w==,type:comment]
    INTERNAL_API_KEY: ENC[AES256_GCM,data:M+jthUrmw1EooISL80puzY0EDA2haghehXHSs+c/r5Zq3EWUiL7/,iv:jHuEguKwHoBan5skQUPc7RwnmZWf/croU4zaislknfc=,tag:Ttm+HPovPJLdnqgYCq/4yg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOEM0QVVlRGI3RmY3NlVh
            eXFDTHFnamkzQy9KSk5pZE4vM0IyV1FyY1VRCkxMNTdMYVF4YUt0eVNaYWhqQTNn
            clZ3QzNGK0xZZ0xKZ2FQRSt4R0p4QlkKLS0tIEFaekhBcDJuRG1jWHFhWGRFQktp
            NG0rYVVBMndvSUtSaGVlY1hUa0dZTTAKokvivx7LMmubgzKgUQv1jobT3jk/Kzgu
            9ld0zyq2UC9mIt/nf7ieA5bK8SevY2lzUCfnBMxJ77Z5zDLa1zDPDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age147ja7n3gpjuwaw8kft7xxwstpnt39u5r36zdxd2t6ughtg77pukqrwx944
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T13:21:01Z"
    mac: ENC[AES256_GCM,data:+eJB9ZwhjIhAgB0h2S4qwwvydDG+66tNzWMadeMMB24UOR2NDdJwK6D9IZn8BJsBXZX7eDXPV+Jj21UfCUfd2VsoSI4JaNl6sZYN0l3uyVBL/hFuxdoy7dsOZbII4xSyVUTDLKkGFKeJLmgbDISb8md8SX8pDZik7hfD7BM1DRo=,iv:O+oRsKn0zeQCjz2MKVe308w5hrZs8QBmqOehj1Lq0U0=,tag:JgT9sv2h/RNlFstU6CU2/A==,type:str]
    version: 3.13.2
