apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: mini-commerce
    labels:
        app.kubernetes.io/part-of: mini-commerce
type: Opaque
stringData:
    DATABASE_USERNAME: ENC[AES256_GCM,data:IaKM5tIm5p0svvkc,iv:utHYWoO8xIzTPNsa9F10ZMKy26S9YTD0j2UOC6ygJlQ=,tag:Q6qx5G5pdFHh2rUhRuCtgw==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:x2R9526WVsWisBWp,iv:c0kqURNZmkRtSy665Pdn69qeaSZBgebCmO0xtPC45i8=,tag:plT4hIiLRuR7hCcDwms5Fw==,type:str]
    REDIS_PASSWORD: ""
    BFF_SECRET_KEY: ENC[AES256_GCM,data:Fm/sonOR+J/fIRrUebxxI7WKL+nzOA==,iv:t03XHpNUUE3NciQVwRc+EsFzKgVF8+4EHWQXXjSicy4=,tag:eBXqzsmt9Vycv/KM7rJV+Q==,type:str]
    SUPABASE_SERVICE_ROLE_KEY: ENC[AES256_GCM,data:Fsr33Q0EDE2RjH0XraZ/OEIFKx9j3+wOZ3ucT3psT2NLPF/SATe3LJ379dIXnGff/oFayjdnLrKFVMvAuPAebKFOADiAiKzGxro50cDRkjDoD6vz1zeLCKNsru38a+TKXcbjXVwvWEd0KbGzaWGDO+n2dwGC1+blMbW9JFj4g0wvbuvVFaV6eOwzn/TWkmKGZZdXmB5zqkrwjFZ5yXCeugRKeZJd6yX6PNnYwNqc3a32bUUPywXp3IF+crc91SsIO3pFV+f9ex1k8tVxkUFP0g0zzqVHRgJBuyw8,iv:vEhQGLP+LPgDOhDxtMQjiuQ7pH5Kgz4/8OcHNic+Rp8=,tag:rNamheB3I0QjkM8wWPRD8g==,type:str]
    TOSS_SECRET_KEY: ENC[AES256_GCM,data:6SF57KudIrvrxg3Q9874XptD66Q8lN8QQojtiY+7NtdPCtTHNsI=,iv:x5+GgJKXbYulD8+xSpnwm/rDHJ6LSBkHWxfdnN28X5o=,tag:QGrmIFC/HJWue4pCJQ0PYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzN2tKNEd1SUwrak96S0tB
            aVNGekRpS0F4Z2MwOFVFaXJ6cmR5dldXWVN3Cmd4SnhDUkxiQnFWRVFrQ29Zc2tZ
            N3dFK3h4ZkJvWjlNekp0NXBIczZLd00KLS0tIFVSditoNjZDN1dldHFDOTRiYXJV
            ZStmWW9zRnRSQktTYTgvSk1kbmlhUUkKjA4BnjeGIbegRzRSbZw3FABpeg0L14vD
            5aDgeiu3JBk9x/dhYmynv8FEENdM+aOcOju+y+Z3iqqGZKx/Ca8Xog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age147ja7n3gpjuwaw8kft7xxwstpnt39u5r36zdxd2t6ughtg77pukqrwx944
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T04:08:24Z"
    mac: ENC[AES256_GCM,data:unfqEWmMr57qS04QGUFHFVp9rq7cD3+0c956q884ekNhZI5YrMNmujW4ZPuyyezF5Cc+yCTnSiRPg5FhdjfhKYwkCTY17QIyggbqC9mAz7Hs0+Vh7ZrH8AstIbsHT7P7uA8eYW4MkRQLRa3gUII8pPiOrvileUUfeNcDgVP+zO4=,iv:Kh+mAS9Y1v4Xy3og/1qo0KLXGejc8an3bBQo7VGn6HA=,tag:YGmHXgD7A8TJ5FuWrJA0Gg==,type:str]
    version: 3.13.2
