apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: mini-commerce
    labels:
        app.kubernetes.io/part-of: mini-commerce
type: Opaque
stringData:
    DATABASE_USERNAME: ENC[AES256_GCM,data:M6KNf326hCbl5Fr7,iv:U1RfRNWVdle5oVR7KOaeRgkiJkFfaGHFiNNBjoNVUQI=,tag:M0qao2M2+8IB/erq7pLYNg==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:A4/INhhAADZUVZV+,iv:8jEDdAdJm+mhJqH5L/KkW+LRArtMpkh8Yz2g5MnGLXs=,tag:JhQxS/fVsjIUE2SfcTF1JQ==,type:str]
    REDIS_PASSWORD: ""
    BFF_SECRET_KEY: ENC[AES256_GCM,data:hrNDbbboczeedl8aIJ0HIsCDvuBnEQ==,iv:ur9n//vhzcJWTs7Qh9zpAWAt3KsvRin9nXfvHtVC8+U=,tag:MHRptesa2XYLpSnqLkl/kQ==,type:str]
    SUPABASE_SERVICE_ROLE_KEY: ENC[AES256_GCM,data:+6zGaswYq3cBQqXD1aVpFIr7I7MBbPfgktcjVBtRqx1uaoc2xR8ke3SjFmA8GJSuVuiqSm96v9AA7ASeXe6FJzBQ9489TJtR+F8ogJNXrkBZbYILrw4pYYgjPLHdgTdUZ4I19STYS8H/vx9E4GEtTAhXFULHbnL7TsWzRqFfeesYyx7i5vQbeAuLj9mm5QIemhFx0oos44MNDtrYpJ23CMK4mrhZbvDsi9/PIEvI7Xcbbx+9rMsZJ4poAl6OdIjUQ/qqKtOO6dWLG0hWiRZw+h55vt1kD2LlIsC3,iv:kImS3U6ZuYrVSXHuXFjBCwtAV4eiMN8ZbZR4QDuHNWI=,tag:348bDoftDKwD7n1wjZboNg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwek9xZTYzRFdRSi9tcGEw
            Yys4L1U3aGhyanJQVnVOWmlrVDlBdThBaDFrCmhnbi9ET2ViRXpLKzZGSk04S0M3
            Kzd5QzJsYjNOdzJKVzMydjY0SGlwK2MKLS0tIHZkcVRUejc2eThqV05FdEUrYzJR
            R1FLVC9mZjVzOGc2Q25lYks2bWhvVUkKzm0pefnDkMxCkGOVxuQ1s+8yYXuaolww
            kxuqP8UGXVigsTE7DYRQH7Ab3FKox1KHTY14RpwE7i/j0+rShZmY+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age147ja7n3gpjuwaw8kft7xxwstpnt39u5r36zdxd2t6ughtg77pukqrwx944
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T03:23:37Z"
    mac: ENC[AES256_GCM,data:A5BAKMP3pucnItorjISSDhNebj0KVAklZ+0BtTHplqLSAwCizSb6cBWd9afM8l3EDl8HUuZBIWGiHtVqI67kL4fq1fo5pXNBVwncD/v9ZzHAsIT1gpyT3db1VqStPOL5eySQ92vSpJ6xHriik/PH5tpJEqVpTBuTOVMD+ahGOiE=,iv:TZYcME9i4EmtVz5FxcaAletZVL9CxfURIhUeBtZdMyU=,tag:GekzUb+5+IZBcbwQwwnREQ==,type:str]
    version: 3.13.2
