-- Flyway baseline (GH #11, GH #20) — orderdb DB.
-- order-api가 단독 소유하는 orderdb 스키마의 통합 스냅샷이다(order-admin/order-batch는 validate-only).
-- 정식 런칭 전(실사용자 없음)이라 기존 증분 마이그레이션(V2~V4)을 이력 보존 없이 하나의 V1으로
-- 통합 재작성했다.
--
-- GH #20(PK 전략 확장): orders.id/customer_id, order_lines.order_id/product_id를 uuid로 전환한다.
--   order_lines.id는 bigint IDENTITY 그대로 유지(자연 시퀀스). orders.payment_key는 Toss가 발급하는
--   문자열 키라 varchar 유지(uuid 아님). 값은 애플리케이션이 UUIDv7로 생성한다.
--
-- inventory_reservations/_lines는 GH #3(ADR-019)에서 inventorydb(inventory-api 소유)로 완전 이관되어
-- orderdb에는 더 이상 존재하지 않는다(과거 V4에서 DROP됐던 死테이블 — fresh baseline에는 처음부터 없음).
--
-- event_publication은 Spring Modulith 아웃박스.

CREATE TABLE public.orders (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone,
    customer_id uuid,
    payment_key character varying(255),
    shipping_address character varying(255),
    shipping_detail_address character varying(255),
    shipping_phone character varying(255),
    shipping_recipient character varying(255),
    shipping_zip_code character varying(255),
    status character varying(255),
    total_amount numeric(38,2),
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING_PAYMENT'::character varying, 'PAID'::character varying, 'PAYMENT_FAILED'::character varying, 'EXPIRED'::character varying, 'CANCELED'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying])::text[])))
);

CREATE TABLE public.order_lines (
    id bigint NOT NULL,
    product_id uuid,
    product_name character varying(255),
    quantity bigint NOT NULL,
    selected_option_value character varying(255),
    unit_price numeric(38,2),
    order_id uuid NOT NULL
);

ALTER TABLE public.order_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Spring Modulith 이벤트 아웃박스 (spring-modulith-starter-jpa).
CREATE TABLE public.event_publication (
    id uuid NOT NULL,
    completion_date timestamp(6) with time zone,
    event_type character varying(255),
    listener_id character varying(255),
    publication_date timestamp(6) with time zone,
    serialized_event character varying(255)
);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.order_lines
    ADD CONSTRAINT order_lines_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.event_publication
    ADD CONSTRAINT event_publication_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.order_lines
    ADD CONSTRAINT fk1smc0s578t2oih21yn9hw6usr FOREIGN KEY (order_id) REFERENCES public.orders(id);
