-- Flyway baseline (GH #11) — orderdb DB.
-- order-api가 단독 소유하는 orderdb 스키마의 현행 스냅샷이다(order-admin/order-batch는 validate-only).
-- 클린 볼륨에 ddl-auto:update로 띄운 실 DB를 pg_dump하여 추출했다(타입/제약이 Hibernate 매핑과
-- 정확히 일치 → ddl-auto:validate 통과 보장). inventory_reservations/_lines는 order-api에 포함된
-- inventory 모듈이 orderdb에 영속화하는 테이블이다. event_publication은 Spring Modulith 아웃박스.

CREATE TABLE public.orders (
    id character varying(255) NOT NULL,
    created_at timestamp(6) with time zone,
    customer_id character varying(255),
    shipping_address character varying(255),
    shipping_detail_address character varying(255),
    shipping_phone character varying(255),
    shipping_recipient character varying(255),
    shipping_zip_code character varying(255),
    status character varying(255),
    total_amount numeric(38,2),
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING_PAYMENT'::character varying, 'PAID'::character varying, 'PAYMENT_FAILED'::character varying, 'EXPIRED'::character varying, 'CANCELED'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying])::text[])))
);

CREATE TABLE public.order_lines (
    id bigint NOT NULL,
    product_id character varying(255),
    product_name character varying(255),
    quantity bigint NOT NULL,
    selected_option_value character varying(255),
    unit_price numeric(38,2),
    order_id character varying(255) NOT NULL
);

ALTER TABLE public.order_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.inventory_reservations (
    id character varying(255) NOT NULL,
    expires_at timestamp(6) with time zone,
    order_id character varying(255),
    status character varying(255),
    CONSTRAINT inventory_reservations_status_check CHECK (((status)::text = ANY ((ARRAY['RESERVED'::character varying, 'CONFIRMED'::character varying, 'RELEASED'::character varying, 'EXPIRED'::character varying])::text[])))
);

CREATE TABLE public.inventory_reservation_lines (
    inventory_reservation_id character varying(255) NOT NULL,
    product_id character varying(255),
    quantity bigint
);

-- Spring Modulith 이벤트 아웃박스 (spring-modulith-starter-jpa).
CREATE TABLE public.event_publication (
    id uuid NOT NULL,
    completion_date timestamp(6) with time zone,
    event_type character varying(255),
    listener_id character varying(255),
    publication_date timestamp(6) with time zone,
    serialized_event character varying(255)
);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.order_lines
    ADD CONSTRAINT order_lines_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.inventory_reservations
    ADD CONSTRAINT inventory_reservations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.event_publication
    ADD CONSTRAINT event_publication_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.order_lines
    ADD CONSTRAINT fk1smc0s578t2oih21yn9hw6usr FOREIGN KEY (order_id) REFERENCES public.orders(id);

ALTER TABLE ONLY public.inventory_reservation_lines
    ADD CONSTRAINT fkc3css0lxqun15o4i57alo4s7v FOREIGN KEY (inventory_reservation_id) REFERENCES public.inventory_reservations(id);
